config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :manhattans
  resources :healthchecks

  root 'manhattans#index'

end

app/models/manhattan.rb
class Manhattan < ActiveRecord::Base
  validates :name, :recipe, :num_cherries, :establishment, :city,
            presence: true
  after_save :expire_manhattan_all_cache
  after_destroy :expire_manhattan_all_cache

  def self.all_cached
    Rails.cache.fetch('Manhattan.all') { all }
  end

  def expire_manhattan_all_cache
    Rails.cache.delete('Manhattan.all')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, length: { maximum: 25 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  # redirect user to login if they are not
  def user_logged_in?
    return if logged_in?
    flash[:alert] = 'You must be logged in to do that!'
    redirect_to request.referrer
  end # user_logged_in?
end

app/controllers/healthchecks_controller.rb
class HealthchecksController < ApplicationController
  def index
    metadata_url = 'http://169.254.169.254/latest/meta-data/instance-id'
    instance_id = `curl #{metadata_url} -m 3`
    instance_id = 'not_an_ec2_instance_bro' if instance_id.empty?
    @host = instance_id
  end
end

app/controllers/manhattans_controller.rb
class ManhattansController < ApplicationController
  before_action :set_manhattan, only: [:show, :edit, :update, :destroy]
  before_action :user_logged_in?, only: [:new, :edit, :create, :update, :destroy]

  # GET /manhattans
  # GET /manhattans.json
  def index
    @manhattans = Manhattan.all_cached
  end

  # GET /manhattans/1
  # GET /manhattans/1.json
  def show
    default_image if @manhattan.image.blank? || @manhattan.cf_image_url.blank?
  end

  # GET /manhattans/new
  def new
    @manhattan = Manhattan.new
  end

  # GET /manhattans/1/edit
  def edit
  end

  # POST /manhattans
  # POST /manhattans.json
  def create
    @manhattan = Manhattan.new(manhattan_params)
    image_name = params['manhattan']['image']

    unless params['manhattan']['image'].blank?
      image = upload_image(image_name)
      if image
        @manhattan.image = image
        @manhattan.cf_image_url = "#{CF_URL}/#{image_name}"
      else
        display_error('Image Upload Failed', :new)
        return false
      end # if
    end # unless

    respond_to do |format|
      if @manhattan.save
        format.html { redirect_to @manhattan, notice: 'Manhattan was successfully created.' }
        format.json { render :show, status: :created, location: @manhattan }
      else
        format.html { render :new }
        format.json { render json: @manhattan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manhattans/1
  # PATCH/PUT /manhattans/1.json
  def update
    respond_to do |format|
      if @manhattan.update(manhattan_params)
        format.html { redirect_to @manhattan, notice: 'Manhattan was successfully updated.' }
        format.json { render :show, status: :ok, location: @manhattan }
      else
        format.html { render :edit }
        format.json { render json: @manhattan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manhattans/1
  # DELETE /manhattans/1.json
  def destroy
    @manhattan.destroy
    respond_to do |format|
      format.html { redirect_to manhattans_url, notice: 'Manhattan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_manhattan
    @manhattan = Manhattan.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def manhattan_params
    params.require(:manhattan).permit(:name, :recipe, :num_cherries, :rocks,
                                      :establishment, :city, :notes, :image)
  end

  # Set default pictures
  def default_image
    ice = "#{ENV['S3_CF_URL']}/manhattan_ice.jpg"
    no_ice = "#{ENV['S3_CF_URL']}/manhattan_splash.jpg"

    if @manhattan.rocks?
      @manhattan.cf_image_url = ice
    else
      @manhattan.cf_image_url = no_ice
    end # if
  end # default_image

  # Upload image to s3
  def upload_image(image)
    # Make an object in bucket for upload
    obj = S3_BUCKET.object("manhattans/#{image.original_filename}")

    # Upload the file
    obj.put(acl: 'public-read', body: image)

    #
    obj.public_url
  rescue => e
    Rails.logger.fatal e
    return false
  end # process_image

  # Handle displaying error pages/codes
  def display_error(err_msg, action)
    respond_to do |format|
      flash[:alert] = err_msg
      format.html { render action }
      format.json { render json: err_msg, status: :unprocessable_entity }
    end # respond_to
  end # display_error
end # class

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      flash[:notice] = "You are logged in as #{user.username}"
      log_in user
      redirect_to root_url
    else
      # Create an error message.
      flash.now[:alert] = 'Invalid user/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # Disable create/update/delete
  #   # GET /users/new
  #   def new
  #     @user = User.new
  #   end
  #
  #   # GET /users/1/edit
  #   def edit
  #   end
  #
  #   # POST /users
  #   # POST /users.json
  #   def create
  #     @user = User.new(user_params)
  #
  #     respond_to do |format|
  #       if @user.save
  #         format.html { redirect_to @user, notice: 'User was successfully created.' }
  #         format.json { render :show, status: :created, location: @user }
  #       else
  #         format.html { render :new }
  #         format.json { render json: @user.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end
  #
  #   # PATCH/PUT /users/1
  #   # PATCH/PUT /users/1.json
  #   def update
  #     respond_to do |format|
  #       if @user.update(user_params)
  #         format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #         format.json { render :show, status: :ok, location: @user }
  #       else
  #         format.html { render :edit }
  #         format.json { render json: @user.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end
  #
  #   # DELETE /users/1
  #   # DELETE /users/1.json
  #   def destroy
  #     @user.destroy
  #     respond_to do |format|
  #       format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #       format.json { head :no_content }
  #     end
  #   end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manhattans_helper.rb
module ManhattansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/healthchecks/index.html.erb
<h2><%= @host %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Manhattan Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>>The Manhattan Project</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav">
          <li class="active"><a href=<%= new_manhattan_path %>>Add Recipe <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if logged_in? %>
              <%= link_to "Logged in as #{@current_user.username} | Logout", logout_path, method: :delete, class: 'navbar-link'  %>
            <% else %>
              <%= link_to "Login", login_path, class: 'navbar-link'  %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <p>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </p>

  <%= yield %>
</div>

  <% if Rails.env.development? %>
    <%= debug(params) %>
  <% end %>
</body>
</html>

app/views/manhattans/_form.html.erb
<%= form_for(@manhattan, multipart: true) do |f| %>
  <% if @manhattan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manhattan.errors.count, "error") %> prohibited this manhattan from being saved:</h2>

      <ul>
      <% @manhattan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :recipe %><br>
    <%= f.text_area :recipe %>
  </div>
  <div class="field">
    <%= f.label :num_cherries, 'Number of Cherries' %><br>
    <%= f.number_field :num_cherries %>
  </div>
  <div class="field">
    <%= f.label :rocks, 'On the Rocks?' %><br>
    <%= f.check_box :rocks %>
  </div>
  <div class="field">
    <%= f.label :establishment %><br>
    <%= f.text_field :establishment %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manhattans/edit.html.erb
<h1>Editing Manhattan</h1>

<%= render 'form' %>

<%= link_to 'Show', @manhattan %> |
<%= link_to 'Back', manhattans_path %>

app/views/manhattans/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Recipe</th>
      <th># Cherries</th>
      <th>On the Rocks?</th>
      <th>Establishment</th>
      <th>City</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manhattans.each do |manhattan| %>
      <tr>
        <td><%= manhattan.name %></td>
        <td><%= manhattan.recipe %></td>
        <td><%= manhattan.num_cherries %></td>
        <td><%= manhattan.rocks %></td>
        <td><%= manhattan.establishment %></td>
        <td><%= manhattan.city %></td>
        <td><%= manhattan.notes %></td>
        <td><%= link_to 'Show', manhattan %></td>
        <td><%= link_to 'Edit', edit_manhattan_path(manhattan) %></td>
        <td><%= link_to 'Destroy', manhattan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/manhattans/new.html.erb
<h1>New Manhattan</h1>

<%= render 'form' %>

<%= link_to 'Back', manhattans_path %>

app/views/manhattans/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @manhattan.name %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @manhattan.recipe %>
</p>

<p>
  <strong>Number of Cherries:</strong>
  <%= @manhattan.num_cherries %>
</p>

<p>
  <strong>On the Rocks?:</strong>
  <%= @manhattan.rocks %>
</p>

<p>
  <strong>Establishment:</strong>
  <%= @manhattan.establishment %>
</p>

<p>
  <strong>City:</strong>
  <%= @manhattan.city %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @manhattan.notes %>
</p>

<img src=<%= @manhattan.cf_image_url %>>
<p>

<%= link_to 'Edit', edit_manhattan_path(@manhattan) %> |
<%= link_to 'Back', manhattans_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>